[project]
name = "llm-text-evaluation-framework"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "sqlmodel>=0.0.24",
    "streamlit>=1.48.0",
]
